remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Angelica's Portfolio Website]
description: [Hi I'm Angelica Jones A Front End Developer!]
